version: '3.7'
services:
  # The web server (e.g., Nginx or Apache)
  # This serves the application and routes traffic.
  app:
    # Use a standard Nginx image
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      # Map the container's port 80 to your host's port 8000
      - '8000:80'
    volumes:
      # Mount the current project directory into the container
      - .:/var/www/html
      # Use a custom Nginx configuration file
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # Nginx needs to connect to the PHP-FPM service
    depends_on:
      - php

  # The PHP-FPM service
  # This processes PHP code (where the "php" command lives).
  php:
    # Use an official PHP-FPM image with a specific version
    image: php:8.3-fpm-alpine
    container_name: laravel_php
    volumes:
      # Mount the current project directory into the container
      - .:/var/www/html
    working_dir: /var/www/html
    # Set up basic environment variables for Laravel/Composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  # (Optional) A database service
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    # Expose the MySQL port to the host
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      # Store database data persistently on your host
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
